name: poetry build and poetry publish

on:
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  publish-to-pypi:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        
      - name: install and configure poetry
        shell: bash
        run: |
          pip install poetry
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: poetry build and publish
        shell: bash
        run: poetry publish --build
