name: Build and push to PyPi

on:
  pull_request:
    branches:
      - main
    types: closed
    paths:
      - quipus/**

jobs:
  ci:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install and configure poetry
        shell: bash
        run: |
          pip install poetry
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

      - name: Bump version
        run: |
          branch_name="${{ github.head_ref }}"

          if [[ "$branch_name" =~ ^(ft/|feat/|feature/) ]]; then
            poetry version minor
          else
            poetry version patch
          fi

      - name: Identify on GitHub
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "action@github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "$(poetry version -s)"

      - name: Create tag
        run: |
          git tag v$(poetry version -s)

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main --tags

      - name: Poetry build and publish
        shell: bash
        run: poetry publish --build
