name: Pylint Check

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          pylint_score=$(pylint src/ | grep 'Your code has been rated at' | awk '{print $7}' | cut -d '/' -f 1)
          if (( $(echo "$pylint_score < 9.5" | bc -l) )); then
            echo "Pylint score is too low: $pylint_score. Minimum required: 9.5"

            cat .github/not_enough_pylint_score.md

            gh pr comment \
              ${{ github.event.pull_request.number }} \
              --body "$(cat .github/not_enough_pylint_score.md)"
            exit 1
          else
            echo "Pylint score is $pylint_score. Passed!"
          fi
